- defaults:
    link:
        relink: true
        create: true

- clean: ['~', '~/bin']

- link:
    #function
    ~/bin:
        glob: true
        path: scripts/*
        relink: true

    #vim
    ~/.vimrc: vimrc
    ~/.vim: vim

    #zsh
    ~/.zshrc:
        path: zsh/zshrc
        force: true
    ~/.on-my-zsh: zsh/oh-my-zsh
    ~/.zgenom: zsh/zgenom  # manage zsh plugins
    
    #tmux
    ~/.tmux.conf: tmux.conf

- asdf:
    - plugin: python
      url: https://github.com/tuvistavie/asdf-python.git
      global: 3.7.4
      versions: 
        - 3.7.4


- shell:
    - [chsh -s $(which zsh), Making zsh the default shell]
    - [git submodule update --init --recursive, Installing submodules]
    - 
     command: ./git/set-gitconfig.sh #set up git
     description: Configuring Git
     stdout: true
     quiet: false


